import { MarkerType } from '@xyflow/react'
import type { FlowTemplate } from '../types'

export const TEMPLATES: FlowTemplate[] = [
  {
    id: 'even-odd',
    name: '1. 짝수 / 홀수 판별하기',
    description: '입력받은 수가 짝수인지 홀수인지 조건문(판단)으로 나누어 판별하는 기본 순서도입니다.',
    nodes: [
      {
        id: 'n1',
        type: 'terminal',
        position: { x: 300, y: 40 },
        data: { label: '시작', kind: 'terminal' },
      },
      {
        id: 'n2',
        type: 'io',
        position: { x: 300, y: 140 },
        data: { label: '숫자 N 입력', kind: 'io' },
      },
      {
        id: 'n3',
        type: 'decision',
        position: { x: 300, y: 240 },
        data: { label: 'N % 2 === 0 ?', kind: 'decision' },
      },
      {
        id: 'n4',
        type: 'io',
        position: { x: 100, y: 380 },
        data: { label: '"짝수입니다" 출력', kind: 'io' },
      },
      {
        id: 'n5',
        type: 'io',
        position: { x: 500, y: 380 },
        data: { label: '"홀수입니다" 출력', kind: 'io' },
      },
      {
        id: 'n6',
        type: 'terminal',
        position: { x: 300, y: 520 },
        data: { label: '끝', kind: 'terminal' },
      },
    ],
    edges: [
      {
        id: 'e1',
        source: 'n1',
        sourceHandle: 'bottom',
        target: 'n2',
        targetHandle: 'target-top',
        type: 'labeled',
        reconnectable: true,
        markerEnd: { type: MarkerType.Arrow, width: 20, height: 20, color: '#64748B' },
      },
      {
        id: 'e2',
        source: 'n2',
        sourceHandle: 'bottom',
        target: 'n3',
        targetHandle: 'target-top',
        type: 'labeled',
        reconnectable: true,
        markerEnd: { type: MarkerType.Arrow, width: 20, height: 20, color: '#64748B' },
      },
      {
        id: 'e3',
        source: 'n3',
        sourceHandle: 'left',
        target: 'n4',
        targetHandle: 'target-top',
        label: '예 (Yes)',
        type: 'labeled',
        reconnectable: true,
        data: { isDecisionEdge: true },
        markerEnd: { type: MarkerType.Arrow, width: 20, height: 20, color: '#64748B' },
      },
      {
        id: 'e4',
        source: 'n3',
        sourceHandle: 'right',
        target: 'n5',
        targetHandle: 'target-top',
        label: '아니오 (No)',
        type: 'labeled',
        reconnectable: true,
        data: { isDecisionEdge: true },
        markerEnd: { type: MarkerType.Arrow, width: 20, height: 20, color: '#64748B' },
      },
      {
        id: 'e5',
        source: 'n4',
        sourceHandle: 'bottom',
        target: 'n6',
        targetHandle: 'target-left',
        type: 'labeled',
        reconnectable: true,
        markerEnd: { type: MarkerType.Arrow, width: 20, height: 20, color: '#64748B' },
      },
      {
        id: 'e6',
        source: 'n5',
        sourceHandle: 'bottom',
        target: 'n6',
        targetHandle: 'target-right',
        type: 'labeled',
        reconnectable: true,
        markerEnd: { type: MarkerType.Arrow, width: 20, height: 20, color: '#64748B' },
      },
    ],
  },
  {
    id: 'sum-loop',
    name: '2. 1부터 5까지의 합 구하기 (반복 구조)',
    description: '변수를 활용하여 1부터 5까지 숫자를 누적해서 더하는 반복문 알고리즘 순서도입니다.',
    nodes: [
      {
        id: 'n1',
        type: 'terminal',
        position: { x: 300, y: 40 },
        data: { label: '시작', kind: 'terminal' },
      },
      {
        id: 'n2',
        type: 'process',
        position: { x: 300, y: 140 },
        data: { label: '합 = 0, N = 1', kind: 'process' },
      },
      {
        id: 'n3',
        type: 'process',
        position: { x: 300, y: 240 },
        data: { label: '합 = 합 + N', kind: 'process' },
      },
      {
        id: 'n4',
        type: 'decision',
        position: { x: 300, y: 340 },
        data: { label: 'N > 5 ?', kind: 'decision' },
      },
      {
        id: 'n5',
        type: 'process',
        position: { x: 100, y: 340 },
        data: { label: 'N = N + 1', kind: 'process' },
      },
      {
        id: 'n6',
        type: 'io',
        position: { x: 300, y: 480 },
        data: { label: '합 출력', kind: 'io' },
      },
      {
        id: 'n7',
        type: 'terminal',
        position: { x: 300, y: 580 },
        data: { label: '끝', kind: 'terminal' },
      },
    ],
    edges: [
      {
        id: 'e1',
        source: 'n1',
        sourceHandle: 'bottom',
        target: 'n2',
        targetHandle: 'target-top',
        type: 'labeled',
        reconnectable: true,
        markerEnd: { type: MarkerType.Arrow, width: 20, height: 20, color: '#64748B' },
      },
      {
        id: 'e2',
        source: 'n2',
        sourceHandle: 'bottom',
        target: 'n3',
        targetHandle: 'target-top',
        type: 'labeled',
        reconnectable: true,
        markerEnd: { type: MarkerType.Arrow, width: 20, height: 20, color: '#64748B' },
      },
      {
        id: 'e3',
        source: 'n3',
        sourceHandle: 'bottom',
        target: 'n4',
        targetHandle: 'target-top',
        type: 'labeled',
        reconnectable: true,
        markerEnd: { type: MarkerType.Arrow, width: 20, height: 20, color: '#64748B' },
      },
      {
        id: 'e4',
        source: 'n4',
        sourceHandle: 'left',
        target: 'n5',
        targetHandle: 'target-right',
        label: '아니오 (No)',
        type: 'labeled',
        reconnectable: true,
        data: { isDecisionEdge: true },
        markerEnd: { type: MarkerType.Arrow, width: 20, height: 20, color: '#64748B' },
      },
      {
        id: 'e5',
        source: 'n5',
        sourceHandle: 'top',
        target: 'n3',
        targetHandle: 'target-left',
        type: 'labeled',
        reconnectable: true,
        markerEnd: { type: MarkerType.Arrow, width: 20, height: 20, color: '#64748B' },
      },
      {
        id: 'e6',
        source: 'n4',
        sourceHandle: 'bottom',
        target: 'n6',
        targetHandle: 'target-top',
        label: '예 (Yes)',
        type: 'labeled',
        reconnectable: true,
        data: { isDecisionEdge: true },
        markerEnd: { type: MarkerType.Arrow, width: 20, height: 20, color: '#64748B' },
      },
      {
        id: 'e7',
        source: 'n6',
        sourceHandle: 'bottom',
        target: 'n7',
        targetHandle: 'target-top',
        type: 'labeled',
        reconnectable: true,
        markerEnd: { type: MarkerType.Arrow, width: 20, height: 20, color: '#64748B' },
      },
    ],
  },
]
